### ISSUE TITLE
How is this done?

### ISSUE THREAD

**Issue by tomhula** [ArtFect/BlockHighlight#5]
Hi, this is just a question not an issue, neither request.

Could you please tell me in more detail how does this work? Because this looks very interesting and very useful. What does it use to render these outlines (like what it is normally in Minecraft uses for) and what kind of packet do you send? Is it documented somewhere?

**Comment by ArtFect** [comment]
Minecraft doesn't use it for anything. This is one of the debug features the developers must have used for the tests, but forgot to disable the rendering of this. This feature works fine in 1.15 and 1.16, but not in 1.17. 
In 1.17 version the rendering has changed slightly and therefore you can only do only green

Here is some documentation: https://wiki.vg/Plugin_channels#minecraft:debug.2Fgame_test_add_marker

Packet is CUSTOM_PAYLOAD, "debug/game_test_add_marker" channel

**Comment by tomhula** [comment]
Alright, thank you so much, this is really useful information.
